name: Test
on: pull_request
defaults:
  run:
    shell: bash
env:
  ENV_VAR_PREFIX: PROP_TEST__
  SELECTED_SINGLE_KEY: 'org.gradle.jvmargs'
  SELECTED_KEYS: 'sourceJavaVersion org.gradle.jvmargs unicode_escapes colon:in:Key'
  SELECTED_SINGLE_NAME: 'my-prop'
  SELECTED_NAMES: 'java-version jvm_args unicode colon'

  NOT_FOUND_STATUS: 54
  SHELL_SETUP: |-
    debugPrintf() {
      local pattern=$1; shift
      printf "::debug::${pattern}" "$@" >&2
    }

    # Reads stdin and replaces one linefeed at the end of the input with "¶". Exits with non-zero status if that LF is
    # missing.
    # Piping a command to this function works around the removal of trailing LFs in command substitution
    # [https://stackoverflow.com/a/15184414] and preserves meaningful LFs.
    # For example, when the command is `jq --raw-output …` and the result is a string with ends with LF, that LF is
    # preserved, and the LF added by jq (like line-based commands generally do) is replaced.
    # This enables precise comparisons.
    replaceLastLF() {
      perl -e '$/ = undef; $_ = <>; ($r = $_) =~ s{\n$}{}; die "missing trailing LF\n" if $r eq $_; printf "%s¶", $r'
    }

    assertEquals() {
      debugPrintf 'assertEquals("%s", "%s")\n' "$1" "$2"
      if [ "$1" = "$2" ]; then
        printf 'ok: "%s" == "%s"\n' "$1" "$2" >&2
      else
        printf 'assertion error: "%s" != "%s"\n' "$1" "$2" >&2
        return 1
      fi
    }

    # Queries a value by calling command $1 with the remaining args and expects it to exit with status $NOT_FOUND_STATUS.
    getAndAssertEquals() {
      local getterFunction=$1; shift
      local key=$1; shift
      local expectedValue=$1; shift
      local value st
      # Invocation of $getterFunction must not ignore its return status. This is why tests use this function in the form
      #   getAndAssertEquals $RESULT_GETTER "$key" "$expectedValue"
      # instead of
      #   assertEquals "$($RESULT_GETTER "$key")" "$expectedValue"
      value="$(set -o pipefail; "$getterFunction" "$key" | replaceLastLF)"
      expectedValue="$(printf '%s\n' "$expectedValue" | replaceLastLF)"
      assertEquals "$value" "$expectedValue"
    }

    # Queries a value by calling command $1 with the remaining args and expects it to exit with status $NOT_FOUND_STATUS.
    getAndAssertUndefined() {
      local getterFunction=$1; shift
      local value st
      if value="$("$getterFunction" "$@")"; then
        printf 'assertion error: %s == "%s", expected undefined\n' "$*" "$value" >&2
        return 1
      elif [ ${st-$?} -eq "$NOT_FOUND_STATUS" ]; then
        printf 'ok: %s is undefined\n' "$*" >&2
      else
        # no error message, assuming failed $getterFunction has already written one
        return $st
      fi
    }

    # The following helper functions to get a value for a given property key from the result have a uniform
    # API (property key as sole argument) so that the actual test code can be identical (and thereby reusable
    # with YAML anchors) for different result types. This leads to some assumptions which might seem
    # a little odd, like variable JSON_OUTPUT_FILE must contain the name of the JSON result instead of passing
    # that name as an argument.

    # Expects JSON as stdin and extracts the value for key $1.
    getJsonValue() {
      local key=$1; shift
      debugPrintf 'getJsonValue("%s")\n' "$key"
      jq --arg k "$key" --raw-output '.[$k] // ("" | halt_error(env.NOT_FOUND_STATUS | tonumber))'
    }

    # Expects JSON in variable RESULT_JSON and extracts the value for key $1.
    getEnvJsonValue() {
      getJsonValue "$@" <<<"$RESULT_JSON"
    }

    # Expects JSON in variable RESULT_JSON and extracts the value for key <output-style encoding of $1>.
    encodeKeyAndGetEnvJsonValue() {
      local key=$1; shift
      local encodedKey
      encodedKey="_$(perl -pe 's=((?!_)[[:punct:]])= sprintf("-%04X", ord($1)) =ge' <<<"$key")"
      getEnvJsonValue "$encodedKey" "$@"
    }

    # Prints the value of the environment variable set for key $1 (when not using a prefix).
    getEnv() {
      local key=$1; shift
      debugPrintf 'getEnv("%s")\n' "$key"
      local st
      if printenv -- "$key"; then
        : # OK
      elif [ ${st-$?} -eq 1 ]; then
        return $NOT_FOUND_STATUS
      else
        # no error message, assuming printenv has already written one
        return $st
      fi
    }

    # Prints the value of the environment variable set for key $1 when using a prefix.
    getEnvWithPrefix() {
      local key=$1; shift
      getEnv "${ENV_VAR_PREFIX}${key}" "$@"
    }

    getFileJsonValue() {
      debugPrintf 'getFileJsonValue("%s") with file contents "%s"\n' "$*" "$(<"$JSON_OUTPUT_FILE")"
      getJsonValue "$@" <"$JSON_OUTPUT_FILE"
    }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - &checkoutStep
      name: Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    ############################################################
    - name: '[act] test (should fail): invalid input: resultType'
      id: error-input-resultType
      continue-on-error: true
      uses: ./
      with:
        file: test/resources/test.properties
        resultType: rt1
    - name: '[assert] test (should fail): invalid input: resultType'
      run: |-
        eval "$SHELL_SETUP"
        assertEquals '${{steps.error-input-resultType.outcome}}' failure

    ############################################################
    - name: '[act] test (should fail): resultType "output-named" without names'
      id: error-resultType-output-without-names
      continue-on-error: true
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}}'
        resultType: 'output-named:'
    - name: '[assert] test (should fail): resultType "output-named" without names'
      run: |-
        eval "$SHELL_SETUP"
        assertEquals '${{steps.error-resultType-output-without-names.outcome}}' failure

    ############################################################
    - name: '[act] test (should fail): resultType "env-named" without names'
      id: error-resultType-env-without-names
      continue-on-error: true
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}}'
        resultType: 'env-named:'
    - name: '[assert] test (should fail): resultType "env-named" without names'
      run: |-
        eval "$SHELL_SETUP"
        assertEquals '${{steps.error-resultType-env-without-names.outcome}}' failure

    ############################################################
    - name: '[act] test (should fail): resultType "output-named" without keys'
      id: error-resultType-output-without-keys
      continue-on-error: true
      uses: ./
      with:
        file: test/resources/test.properties
        resultType: 'output-named:a b'
    - name: '[assert] test (should fail): resultType "output-named" without keys'
      run: |-
        eval "$SHELL_SETUP"
        assertEquals '${{steps.error-resultType-output-without-keys.outcome}}' failure

    ############################################################
    - name: '[act] test (should fail): resultType "env-named" without keys'
      id: error-resultType-env-without-keys
      continue-on-error: true
      uses: ./
      with:
        file: test/resources/test.properties
        resultType: 'env-named:a b'
    - name: '[assert] test (should fail): resultType "env-named" without keys'
      run: |-
        eval "$SHELL_SETUP"
        assertEquals '${{steps.error-resultType-env-without-keys.outcome}}' failure

    ############################################################
    # This tests a subset of test case multi-output, but with hard-coded encoding from property key to output
    # name (instead of re-implemented).
    # It also demonstrates how you'd usually use outputs with one environment variable per output.
    - name: '[act] test: query multiple properties as action outputs (simple)'
      id: multi-output-simple
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}} dash-in-Key'
    - name: '[assert] test: query multiple properties as action outputs (simple)'
      env:
        RESULT_SJV:     ${{steps.multi-output-simple.outputs._sourceJavaVersion}}
        RESULT_JVMARGS: ${{steps.multi-output-simple.outputs._org-002Egradle-002Ejvmargs}}
        RESULT_COLONK:  ${{steps.multi-output-simple.outputs._colon-003Ain-003AKey}}
        RESULT_DASHK:   ${{steps.multi-output-simple.outputs._dash-002Din-002DKey}}
        RESULT_UNI:     ${{steps.multi-output-simple.outputs._unicode_escapes}}
      run: |-
        eval "$SHELL_SETUP"
        assertEquals "$RESULT_SJV"     '21'
        assertEquals "$RESULT_JVMARGS" '-ea -showversion'
        assertEquals "$RESULT_COLONK"  'c'
        assertEquals "$RESULT_DASHK"   'd'
        assertEquals "$RESULT_UNI"     'a«,»c'

    ############################################################
    - name: '[act] test: query all properties as action outputs'
      id: all-output
      uses: ./
      with:
        file: test/resources/test.properties
    - name: '[assert] test: query all properties as action outputs'
      env:
        RESULT_JSON: ${{toJSON(steps.all-output.outputs)}}
        RESULT_GETTER: encodeKeyAndGetEnvJsonValue
      run: &validateAllImpl |-
        eval "$SHELL_SETUP"
        getAndAssertEquals "$RESULT_GETTER" sourceJavaVersion   '21'
        getAndAssertEquals "$RESULT_GETTER" targetJavaVersion   '17'
        getAndAssertEquals "$RESULT_GETTER" org.gradle.jvmargs  '-ea -showversion'
        getAndAssertEquals "$RESULT_GETTER" colon:in:Key        'c'
        getAndAssertEquals "$RESULT_GETTER" colonInValue        'cv:'
        getAndAssertEquals "$RESULT_GETTER" dash-in-Key         'd'
        getAndAssertEquals "$RESULT_GETTER" dashInValue         'd-'
        getAndAssertEquals "$RESULT_GETTER" empty               ''
        getAndAssertEquals "$RESULT_GETTER" null                'null'
        getAndAssertEquals "$RESULT_GETTER" unicode_escapes     'a«,»c'
        getAndAssertEquals "$RESULT_GETTER" whitespace_escapes  $'A\tB\fC C\r\n\nD'
        getAndAssertEquals "$RESULT_GETTER" trailing_linefeed_1 $'one trailing LF\n'
        getAndAssertEquals "$RESULT_GETTER" trailing_linefeed_2 $'two trailing LFs\n\n'
        getAndAssertEquals "$RESULT_GETTER" dash_1              '-'
        getAndAssertEquals "$RESULT_GETTER" dash_2              '--'
        getAndAssertEquals "$RESULT_GETTER" dash_3              '---'
        getAndAssertEquals "$RESULT_GETTER" dash_4              '----'
        getAndAssertEquals "$RESULT_GETTER" dash_5              '-----'
        getAndAssertEquals "$RESULT_GETTER" dash_6              '------'
        getAndAssertEquals "$RESULT_GETTER" dash_7              '-------'
        getAndAssertEquals "$RESULT_GETTER" dash_8              '--------'
        getAndAssertEquals "$RESULT_GETTER" dash_9              '---------'
        getAndAssertEquals "$RESULT_GETTER" dash_10             '----------'
        getAndAssertEquals "$RESULT_GETTER" dash_11             '-----------'
        getAndAssertEquals "$RESULT_GETTER" dash_12             '------------'
        getAndAssertEquals "$RESULT_GETTER" dash_3_4_1          $'---\n----\n-'
        getAndAssertEquals "$RESULT_GETTER" dash_3_4_8_1        $'---\n----\n--------\n-'

    ############################################################
    - name: '[act] test: query multiple properties as action outputs'
      id: multi-output
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}}'
    - name: '[assert] test: query multiple properties as action outputs'
      env:
        RESULT_JSON: ${{toJSON(steps.multi-output.outputs)}}
        RESULT_GETTER: encodeKeyAndGetEnvJsonValue
      run: &validateMultiImpl |-
        eval "$SHELL_SETUP"
        getAndAssertEquals "$RESULT_GETTER" sourceJavaVersion  '21'
        getAndAssertEquals "$RESULT_GETTER" org.gradle.jvmargs '-ea -showversion'
        getAndAssertEquals "$RESULT_GETTER" colon:in:Key       'c'
        getAndAssertEquals "$RESULT_GETTER" unicode_escapes    'a«,»c'

        getAndAssertUndefined "$RESULT_GETTER" targetJavaVersion
        getAndAssertUndefined "$RESULT_GETTER" colonInValue
        getAndAssertUndefined "$RESULT_GETTER" dash-in-Key
        getAndAssertUndefined "$RESULT_GETTER" dashInValue
        getAndAssertUndefined "$RESULT_GETTER" empty
        getAndAssertUndefined "$RESULT_GETTER" null
        getAndAssertUndefined "$RESULT_GETTER" whitespace_escapes
        getAndAssertUndefined "$RESULT_GETTER" trailing_linefeed_1
        getAndAssertUndefined "$RESULT_GETTER" trailing_linefeed_2
        getAndAssertUndefined "$RESULT_GETTER" dash_1
        getAndAssertUndefined "$RESULT_GETTER" dash_2
        getAndAssertUndefined "$RESULT_GETTER" dash_3
        getAndAssertUndefined "$RESULT_GETTER" dash_4
        getAndAssertUndefined "$RESULT_GETTER" dash_5
        getAndAssertUndefined "$RESULT_GETTER" dash_6
        getAndAssertUndefined "$RESULT_GETTER" dash_7
        getAndAssertUndefined "$RESULT_GETTER" dash_8
        getAndAssertUndefined "$RESULT_GETTER" dash_9
        getAndAssertUndefined "$RESULT_GETTER" dash_10
        getAndAssertUndefined "$RESULT_GETTER" dash_11
        getAndAssertUndefined "$RESULT_GETTER" dash_12
        getAndAssertUndefined "$RESULT_GETTER" dash_3_4_1
        getAndAssertUndefined "$RESULT_GETTER" dash_3_4_8_1

    ############################################################
    - name: '[act] test: query multiple properties as action outputs of given names'
      id: multi-output-named
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}}'
        resultType: 'output-named:${{env.SELECTED_NAMES}}'
    - name: '[assert] test: query multiple properties as action outputs of given names'
      env:
        RESULT_JSON: ${{toJSON(steps.multi-output-named.outputs)}}
        # Output names specified as input are not subject to encoding (prefix "_", replace punctuation except "_"):
        RESULT_GETTER: getEnvJsonValue
      run: &validateMultiNamedImpl |-
        eval "$SHELL_SETUP"
        getAndAssertEquals "$RESULT_GETTER" java-version '21'
        getAndAssertEquals "$RESULT_GETTER" jvm_args     '-ea -showversion'
        getAndAssertEquals "$RESULT_GETTER" colon        'c'
        getAndAssertEquals "$RESULT_GETTER" unicode      'a«,»c'

        # The outputs with the default names are not set:
        getAndAssertUndefined "$RESULT_GETTER" sourceJavaVersion
        getAndAssertUndefined "$RESULT_GETTER" org.gradle.jvmargs
        getAndAssertUndefined "$RESULT_GETTER" colon:in:Key
        getAndAssertUndefined "$RESULT_GETTER" unicode_escapes

        # Outputs for non-selected keys are not set, for example:
        getAndAssertUndefined "$RESULT_GETTER" colonInValue
        getAndAssertUndefined "$RESULT_GETTER" dash_1

    ############################################################
    - name: '[act] test: query multiple properties as action outputs of given name'
      id: multi-output-named1
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}}'
        resultType: 'output-named:${{env.SELECTED_SINGLE_NAME}}'
    - name: '[assert] test: query multiple properties as action outputs of given name'
      env:
        RESULT_JSON: ${{toJSON(steps.multi-output-named1.outputs)}}
        # Output names specified as input are not subject to encoding (prefix "_", replace punctuation except "_"):
        RESULT_GETTER: getEnvJsonValue
      run: &validateMultiNamed1Impl |-
        eval "$SHELL_SETUP"
        getAndAssertEquals "$RESULT_GETTER" my-prop 'c'

        # The outputs with the default names are not set:
        getAndAssertUndefined "$RESULT_GETTER" sourceJavaVersion
        getAndAssertUndefined "$RESULT_GETTER" org.gradle.jvmargs
        getAndAssertUndefined "$RESULT_GETTER" colon:in:Key
        getAndAssertUndefined "$RESULT_GETTER" unicode_escapes

        # Outputs for non-selected keys are not set, for example:
        getAndAssertUndefined "$RESULT_GETTER" colonInValue
        getAndAssertUndefined "$RESULT_GETTER" dash_1

    ############################################################
    - name: '[act] test: query single property as action outputs'
      id: single-output
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_SINGLE_KEY}}'
    - name: '[assert] test: query multiple properties as action outputs'
      env:
        RESULT_JSON: ${{toJSON(steps.single-output.outputs)}}
        RESULT_GETTER: encodeKeyAndGetEnvJsonValue
      run: &validateSingleImpl |-
        eval "$SHELL_SETUP"
        getAndAssertEquals "$RESULT_GETTER" org.gradle.jvmargs '-ea -showversion'

        getAndAssertUndefined "$RESULT_GETTER" sourceJavaVersion
        getAndAssertUndefined "$RESULT_GETTER" targetJavaVersion
        getAndAssertUndefined "$RESULT_GETTER" colon:in:Key
        getAndAssertUndefined "$RESULT_GETTER" colonInValue
        getAndAssertUndefined "$RESULT_GETTER" dash-in-Key
        getAndAssertUndefined "$RESULT_GETTER" dashInValue
        getAndAssertUndefined "$RESULT_GETTER" empty
        getAndAssertUndefined "$RESULT_GETTER" null
        getAndAssertUndefined "$RESULT_GETTER" whitespace_escapes
        getAndAssertUndefined "$RESULT_GETTER" trailing_linefeed_1
        getAndAssertUndefined "$RESULT_GETTER" trailing_linefeed_2
        getAndAssertUndefined "$RESULT_GETTER" unicode_escapes
        getAndAssertUndefined "$RESULT_GETTER" dash_1
        getAndAssertUndefined "$RESULT_GETTER" dash_2
        getAndAssertUndefined "$RESULT_GETTER" dash_3
        getAndAssertUndefined "$RESULT_GETTER" dash_4
        getAndAssertUndefined "$RESULT_GETTER" dash_5
        getAndAssertUndefined "$RESULT_GETTER" dash_6
        getAndAssertUndefined "$RESULT_GETTER" dash_7
        getAndAssertUndefined "$RESULT_GETTER" dash_8
        getAndAssertUndefined "$RESULT_GETTER" dash_9
        getAndAssertUndefined "$RESULT_GETTER" dash_10
        getAndAssertUndefined "$RESULT_GETTER" dash_11
        getAndAssertUndefined "$RESULT_GETTER" dash_12
        getAndAssertUndefined "$RESULT_GETTER" dash_3_4_1
        getAndAssertUndefined "$RESULT_GETTER" dash_3_4_8_1

    ############################################################
    - name: '[act] test: query all properties as JSON action output'
      id: all-json
      uses: ./
      with:
        file: test/resources/test.properties
        resultType: json
    - name: '[assert] test: query all properties as JSON action output'
      env:
        RESULT_JSON: ${{steps.all-json.outputs.json}}
        RESULT_GETTER: getEnvJsonValue
      run: *validateAllImpl

    ############################################################
    - name: '[act] test: query multiple properties as JSON action output'
      id: multiple-json
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}}'
        resultType: json
    - name: '[assert] test: query multiple properties as JSON action output'
      env:
        RESULT_JSON: ${{steps.multiple-json.outputs.json}}
        RESULT_GETTER: getEnvJsonValue
      run: *validateMultiImpl

    ############################################################
    - name: '[arrange] test: query multiple properties as JSON file (creating file)'
      id: multiple-json-file-create-arrange
      run: |-
        parentDir=$(mktemp --directory --dry-run --tmpdir=. test_json-file_multi_create_XXXXXX)
        file=$parentDir/out/result.json
        printf 'file=%s\n' "$file" | tee -- "$GITHUB_OUTPUT"
        # ⇒ action must create at least two parent dirs
    - name: '[act] test: query multiple properties as JSON file (creating file)'
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}}'
        resultType: 'json-file:${{steps.multiple-json-file-create-arrange.outputs.file}}'
    - name: '[assert] test: query multiple properties as JSON file (creating file)'
      env:
        JSON_OUTPUT_FILE: ${{steps.multiple-json-file-create-arrange.outputs.file}}
        RESULT_GETTER: getFileJsonValue
      run: *validateMultiImpl

    ############################################################
    - name: '[arrange] test: query multiple properties as JSON file (overwriting file)'
      id: multiple-json-file-overwrite-arrange
      run: |-
        file=$(mktemp --tmpdir=. test_json-file_multi_overwrite_XXXXXX.json)
        # Write longer contents than the expected output. ⇒ If the action does not truncate, there will be
        # non-parseable remains and parsing in function getFileJsonValue will fail.
        for ((i=0; i<100; i++)); do printf 'This is ¬ JS}ON. '; done >"$file"
        ls -lAF -- "$file"
        printf 'file=%s\n' "$file" | tee -- "$GITHUB_OUTPUT"
    - name: '[act] test: query multiple properties as JSON file (overwriting file)'
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}}'
        resultType: 'json-file:${{steps.multiple-json-file-overwrite-arrange.outputs.file}}'
    - name: '[assert] test: query multiple properties as JSON file (overwriting file)'
      env:
        JSON_OUTPUT_FILE: ${{steps.multiple-json-file-overwrite-arrange.outputs.file}}
        RESULT_GETTER: getFileJsonValue
      run: *validateMultiImpl

    ############################################################
    - name: '[arrange] test: query all properties as JSON file'
      id: all-json-file-arrange
      # Distinction between creating and overwriting need not be tested again.
      # This test just uses an existing empty file.
      run: |-
        printf 'file=%s\n' "$(mktemp --tmpdir=. test_json-file_all_XXXXXX.json)" | tee -- "$GITHUB_OUTPUT"
    - name: '[act] test: query all properties as JSON file'
      uses: ./
      with:
        file: test/resources/test.properties
        resultType: 'json-file:${{steps.all-json-file-arrange.outputs.file}}'
    - name: '[assert] test: query all properties as JSON file'
      env:
        JSON_OUTPUT_FILE: ${{steps.all-json-file-arrange.outputs.file}}
        RESULT_GETTER: getFileJsonValue
      run: *validateAllImpl


  # Each test which sets environment variables is a separate job to be independant of other tests.
  ############################################################
  test-all-env:
    runs-on: ubuntu-latest
    steps:
    - *checkoutStep
    - name: '[act] test: query all properties as environment variables'
      uses: ./
      with:
        file: test/resources/test.properties
        resultType: env
    - name: '[assert] test: query all properties as environment variables'
      env:
        RESULT_GETTER: getEnv
      run: *validateAllImpl

  ############################################################
  test-multi-env:
    runs-on: ubuntu-latest
    steps:
    - *checkoutStep
    - name: '[act] test: query multiple properties as environment variables'
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}}'
        resultType: env
    - name: '[assert] test: query multiple properties as environment variables'
      env:
        RESULT_GETTER: getEnv
      run: *validateMultiImpl

  ############################################################
  test-multi-env-named:
    runs-on: ubuntu-latest
    steps:
    - *checkoutStep
    - name: '[act] test: query multiple properties as environment variables of given names'
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}}'
        resultType: 'env-named:${{env.SELECTED_NAMES}}'
    - name: '[assert] test: query multiple properties as environment variables of given names'
      env:
        RESULT_GETTER: getEnv
      run: *validateMultiNamedImpl

  ############################################################
  test-multi-env-named1:
    runs-on: ubuntu-latest
    steps:
    - *checkoutStep
    - name: '[act] test: query multiple properties as environment variables of given names'
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}}'
        resultType: 'env-named:${{env.SELECTED_SINGLE_NAME}}'
    - name: '[assert] test: query multiple properties as environment variables of given names'
      env:
        RESULT_GETTER: getEnv
      run: *validateMultiNamed1Impl

  ############################################################
  test-single-env:
    runs-on: ubuntu-latest
    steps:
    - *checkoutStep
    - name: '[act] test: query single property as environment variable'
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_SINGLE_KEY}}'
        resultType: env
    - name: '[assert] test: query single property as environment variable'
      env:
        RESULT_GETTER: getEnv
      run: *validateSingleImpl

  ############################################################
  test-all-env-with-prefix:
    runs-on: ubuntu-latest
    steps:
    - *checkoutStep
    - name: '[act] test: query all properties as environment variables with prefix'
      uses: ./
      with:
        file: test/resources/test.properties
        resultType: 'env:${{env.ENV_VAR_PREFIX}}'
    - name: '[assert] test: query all properties as environment variables'
      env:
        RESULT_GETTER: getEnvWithPrefix
      run: *validateAllImpl

  ############################################################
  test-multi-env-with-prefix:
    runs-on: ubuntu-latest
    steps:
    - *checkoutStep
    - name: '[act] test: query multiple properties as environment variables with prefix'
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_KEYS}}'
        resultType: 'env:${{env.ENV_VAR_PREFIX}}'
    - name: '[assert] test: query multiple properties as environment variables with prefix'
      env:
        RESULT_GETTER: getEnvWithPrefix
      run: *validateMultiImpl

  ############################################################
  test-single-env-with-prefix:
    runs-on: ubuntu-latest
    steps:
    - *checkoutStep
    - name: '[act] test: query single property as environment variable with prefix'
      uses: ./
      with:
        file: test/resources/test.properties
        keys: '${{env.SELECTED_SINGLE_KEY}}'
        resultType: 'env:${{env.ENV_VAR_PREFIX}}'
    - name: '[assert] test: query single property as environment variable with prefix'
      env:
        RESULT_GETTER: getEnvWithPrefix
      run: *validateSingleImpl
