name: Test
on: pull_request
defaults:
  run:
    shell: bash
env:
  SHELL_SETUP: |-
    function assertEquals() {
      if [ "$1" = "$2" ]; then
        printf 'ok: "%s" == "%s"\n' "$1" "$2" >&2
      else
        printf 'assertion error: "%s" != "%s"\n' "$1" "$2" >&2
        return 1
      fi
    }
    function jsonGet() {
      local key=$1; shift
      jq --arg k "$key" --raw-output '.[$k] // ""'
    }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - &checkoutStep
      name: Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'test (should fail): invalid input: resultType'
      id: error-input-resultType
      continue-on-error: true
      uses: ./
      with:
        file: test/resources/test.properties
        resultType: rt1
    - name: 'validate "test (should fail): invalid input: resultType"'
      run: |-
        eval "$SHELL_SETUP"
        assertEquals '${{steps.error-input-resultType.outcome}}' failure

    - name: 'test: query all properties as action outputs'
      id: all-output
      uses: ./
      with:
        file: test/resources/test.properties
    - name: 'validate "test: query all properties as action outputs"'
      env:
        RESULT_SJV: ${{steps.all-output.outputs._sourceJavaVersion}}
        RESULT_TJV: ${{steps.all-output.outputs._targetJavaVersion}}
        RESULT_GRO: ${{steps.all-output.outputs._org-002Egradle-002Ejvmargs}}
      run: |-
        eval "$SHELL_SETUP"
        assertEquals "$RESULT_SJV" 21
        assertEquals "$RESULT_TJV" 17
        assertEquals "$RESULT_GRO" '-ea -showversion'

    - name: 'test: query multiple properties as action outputs'
      id: multi-output
      uses: ./
      with:
        file: test/resources/test.properties
        keys: 'sourceJavaVersion targetJavaVersion'
    - name: 'validate "test: query multiple properties as action outputs"'
      env:
        RESULT_SJV: ${{steps.multi-output.outputs._sourceJavaVersion}}
        RESULT_TJV: ${{steps.multi-output.outputs._targetJavaVersion}}
      run: |-
        eval "$SHELL_SETUP"
        assertEquals "$RESULT_SJV" 21
        assertEquals "$RESULT_TJV" 17

    - name: 'test: query all properties as JSON action output'
      id: all-json
      uses: ./
      with:
        file: test/resources/test.properties
        resultType: json
    - name: 'validate "test: query all properties as JSON action output"'
      env:
        RESULT: ${{steps.all-json.outputs.json}}
      run: |-
        eval "$SHELL_SETUP"
        jq <<<"$RESULT" # assert parseable (and print)
        # check some values:
        assertEquals "$(jsonGet 'unicode_escapes' <<<"$RESULT")" 'a«,»c'
        assertEquals "$(jsonGet 'colon:in:Key'    <<<"$RESULT")" 'c'
        # assert size >= 10:
        test "$(jq --raw-output 'keys | length' <<<"$RESULT")" -ge 10

    - name: 'test: query multiple properties as JSON action output'
      id: multiple-json
      uses: ./
      with:
        file: test/resources/test.properties
        keys: 'colon:in:Key colonInValue unicode_escapes'
        resultType: json
    - name: 'validate "test: query multiple properties as JSON action output"'
      env:
        RESULT: ${{steps.multiple-json.outputs.json}}
      run: |-
        eval "$SHELL_SETUP"
        assertEquals "$(jsonGet 'unicode_escapes' <<<"$RESULT")" 'a«,»c'
        assertEquals "$(jsonGet 'colonInValue'    <<<"$RESULT")" 'cv:'
        assertEquals "$(jsonGet 'colon:in:Key'    <<<"$RESULT")" 'c'
        # assert size 3 (i.e. no additional results):
        assertEquals "$(jq --raw-output 'keys | length' <<<"$RESULT")" 3

    - name: 'test: query multiple properties as JSON file'
      uses: ./
      with:
        file: test/resources/test.properties
        keys: 'colon:in:Key colonInValue unicode_escapes'
        resultType: json-file:tmp/multi.json
    - name: 'validate "test: query multiple properties as JSON file"'
      run: |-
        eval "$SHELL_SETUP"
        result=$(<tmp/multi.json) # read file only once
        assertEquals "$(jsonGet 'unicode_escapes' <<<"$result")" 'a«,»c'
        assertEquals "$(jsonGet 'colonInValue'    <<<"$result")" 'cv:'
        assertEquals "$(jsonGet 'colon:in:Key'    <<<"$result")" 'c'
        # assert size 2 (i.e. no additional results):
        assertEquals "$(jq --raw-output 'keys | length' <<<"$result")" 3

  # Each test which sets environment variables is a separate job to be independant of other tests.
  test-all-env:
    runs-on: ubuntu-latest
    steps:
    - *checkoutStep
    - name: 'test: query all properties as environment variables'
      uses: ./
      with:
        file: test/resources/test.properties
        resultType: env
    - name: 'validate "test: query all properties as environment variables"'
      run: |-
        eval "$SHELL_SETUP"
        assertEquals "$sourceJavaVersion"  21
        assertEquals "$targetJavaVersion"  17
        assertEquals "$(printenv org.gradle.jvmargs)" '-ea -showversion'
        assertEquals "$whitespace_escapes" $'a\fb\rc\n'
        assertEquals "$unicode_escapes"    'a«,»c'

  test-multi-env:
    runs-on: ubuntu-latest
    steps:
    - *checkoutStep
    - name: 'test: query multiple properties as environment variables'
      uses: ./
      with:
        file: test/resources/test.properties
        keys: 'sourceJavaVersion org.gradle.jvmargs unicode_escapes'
        resultType: env
    - name: 'validate "test: query multiple properties as environment variables"'
      run: |-
        eval "$SHELL_SETUP"
        assertEquals "$sourceJavaVersion"  21
        assertEquals "$(printenv org.gradle.jvmargs)" '-ea -showversion'
        assertEquals "$unicode_escapes"    'a«,»c'
        assertEquals "$targetJavaVersion"  ''
        assertEquals "$whitespace_escapes" ''
